# Site settings
title: Sophie Drake
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sophiedrake.github.io" # the base hostname & protocol for your site
twitter_username: SophieDrake
github_username:  sophiedrake

# Build settings
markdown: kramdown
